### ISSUE TITLE
AKS samples don't work in AKS 1.2.2+ and don't deploy

### ISSUE THREAD

**Issue by sambetts** [microsoftgraph/microsoft-graph-comms-samples#591]
**Describe the issue**
AKS samples don't work in AKS 1.2.2, specifically APIs which are deprecated:

cert-manager.io/v1alpha2
networking.k8s.io/v1beta1

Source: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

After updating the template to use supported APIs with the following template changes means it'll deploy:

ingress.yaml:
```yaml
{{- $fullName := include "fullName" . -}}
{{- $namespace := include "namespace" . -}}
apiVersion: networking.k8s.io/v1

[snip]

  rules:
  - host: {{ include "hostName" . }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}-routing
            port: 
              number: 443
        path: /
        pathType: Prefix
```

cluster-issuer.yaml:
```yaml
apiVersion: cert-manager.io/v1
```
...but it fails to get a certificate from letsencrypt, and therefore never gets the SSL certificate.
